spring:
  datasource:
    url: jdbc:h2:file:./db_dev
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

custom:
  jwt:
    secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
    exp: "#{60 * 60 * 30}"
    refresh-exp: "#{60 * 60 * 60 * 24 * 30}"
logging:
  level:
    org.springframework.security: debug
