server:
  port: ${PORT:8080}  # 환경변수 PORT가 없으면 기본값 8080 사용

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # active 프로파일 설정
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/yourdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER_NAME}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}  # 개발: update, 운영: validate 또는 none 권장
    show-sql: ${JPA_SHOW_SQL:false}


  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:your_client_id}
            client-secret: ${GITHUB_CLIENT_SECRET:your_client_secret}
            scope: read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

logging:
  level:
    root: INFO
    com.example: DEBUG
  file:
    name: ${LOG_FILE_PATH:./logs/app.log}  # 로그 파일 경로를 환경변수로 지정


